#!/bib/sh

# Google it
google() {
	local term="$@"
	local url="http://www.google.com/search?q=${term// /+}"
	$BROWSER -a Google\ Chrome "$url"
}

# Github
github() {
	local term="$@"
	local url="http://www.github.com/${term// /+}"
	$BROWSER "$url"
}

# Google Console
gconsole() {
	local term="$@"
	local url="https://console.developers.google.com/home/dashboard?project=${term// /+}"
	$BROWSER "$url"
}

# Reddit
reddit() {
	local term="$@"
	local url="https://www.reddit.com/r/${term// /+}/"
	$BROWSER -a Google\ Chrome "$url"
}

k-secrets() {
	kubectl get secrets $@ -ojson | jq '{name: .metadata.name, data: .data | map_values(@base64d)}'
}
