#!/bib/sh

# Google it
google() {
  local term="$@"
  local url="http://www.google.com/search?q=${term// /+}"
  $BROWSER "$url"
}

# Github
github() {
  local term="$@"
  local url="http://www.github.com/${term// /+}"
  $BROWSER "$url"
}

# Google Console
gconsole() {
  local term="$@"
  local url="https://console.developers.google.com/home/dashboard?project=${term// /+}"
  $BROWSER "$url"
}

# Siprev no dell
siprev() {
    local term="$@"
    local url="http://192.168.0.107:8089/SIPREV"
    $BROWSER "$url"
}

siprevwin() {
    local term="$@"
    local url="http://192.168.0.112:8089/SIPREV"
    $BROWSER "$url"
}

transmission() {
	local term="$@"
	local url="http://192.168.0.17:9091"
	$BROWSER "$url"
}
