#!/usr/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
   export BROWSER="/usr/bin/open"

#   export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
#   export MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
#   export PATH="/usr/local/opt/texinfo/bin:$PATH"
#   export PATH=/usr/local/opt/gettext/bin:$PATH

export NODE_PATH=/usr/local/opt/node@8

export PATH=$HOME/.bin:./bin:./.bundle/bin:${GPG_BIN}:/usr/local/bin:/usr/local/opt/coreutils/libexec/gnubin:/usr/local/opt/python/libexec/bin:${NODE_PATH}/bin:${YARN_BIN_PATH}:/usr/local/lib:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/opt/local/bin

export MANPATH=/usr/local/opt/gnu-sed/libexec/gnuman:$MANPATH


  #fzf
  [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

 #pyenv
#  export PYENV_ROOT="$HOME/.pyenv"
#  export PATH="$PYENV_ROOT/bin:$PATH"
#  eval "$(pyenv init -)"
fi
