#!/bin/bash

alias rm='rm -i'


alias df='df -h'
alias du='du -h'
alias dus='du -hs'

alias ls='ls -lh --color=tty'
alias ll='ls -lah --color=tty'
alias la='ls -A'
alias l='ls -CF'
alias lsdir="ls -d */  | cut -f1 -d'/'"

alias lci='colorls -r'
alias lc='colorls'

alias elc='$EDITOR -nw $(gem which colorls)/../yaml/'

alias e='$EDITOR'
alias et="$EDITOR -nw"


# docker
alias dimgs='docker images'
alias dps='docker ps'

# docker-compose
alias dcp='docker-compose'
alias dcpu='docker-compose up'
alias dcpud='docker-compose up -d'

if [[ "$OSTYPE" == "darwin"* ]]; then
  alias cask='brew cask'
fi

# servidor casa plex
alias plex='ssh adminuser@192.168.0.210'
