#!/bib/sh

# Google it
google() {
  local term="$@"
  local url="http://www.google.com/search?q=${term// /+}"
  $BROWSER -a Google\ Chrome "$url"
}

# Github
github() {
  local term="$@"
  local url="http://www.github.com/${term// /+}"
  $BROWSER "$url"
}

# Google Console
gconsole() {
  local term="$@"
  local url="https://console.developers.google.com/home/dashboard?project=${term// /+}"
  $BROWSER "$url"
}

# Jenkins
jenkins() {
    local term="$@"
    local url="http://ci.sisprev.net.br/login?from=%2Fmanage"
    $BROWSER -a Google\ Chrome "$url"
}

# Reddit
reddit() {
    local term="$@"
    local url="https://www.reddit.com/r/${term// /+}/"
    $BROWSER -a Google\ Chrome "$url"
}
